DELETE FROM data1;


INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES ('Carl', 'Frederiksen', 'Carl@gmail.com', 170, 22, 41);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES ('Betim', 'Hamidi', 'Betim@gmail.com', 187, 22, 44);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES ('Mads', 'byth', 'mads@gmail.com', 190, 23, 44);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES( 'Kate', 'Li','Kate.Li@yahoo.com',  196, 58, 53);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Preston', 'Gates', 'Preston.Gates@outlook.com',  183, 58, 25);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Lucy', 'Proctor', 'Lucy.Proctor@gmail.com',  209, 65, 22);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Braylon', 'Downs', 'Braylon.Downs@outlook.com',  166, 34, 43);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Landin', 'Murphy', 'Landin.Murphy@hotmail.com', 	187, 49, 40);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Greyson', 'Davila', 'Greyson.Davila@hotmail.com', 	187, 89, 23);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Selah', 'Lyons', 'Selah.Lyons@hotmail.com',  158, 54, 39);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Riya', 'Shaw', 'Riya.Shaw@outlook.com',  219, 87, 34);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Nataly', 'Hebert', 'Nataly.Hebert@gmail.com',  186, 95, 44);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Marilyn', 'Mosley', 'Marilyn.Mosley@gmail.com',  152, 32,29);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Keith', 'Pittman', 'Keith.Pittman@gmail.com',  178, 67, 34);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Yasmine', 'Lucas', 'Yasmine.Lucas@gmail.com',  205, 71, 24);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Dana', 'James', 'Dana.James@gmail.com',  152, 77, 30);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Jaylin', 'Chung', 'Jaylin.Chung@gmail.com',  218, 90, 46);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Naomi', 'Braun', 'Naomi.Braun@gmail.com',  214, 42, 60);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Damaris', 'Key', 'Damaris.Key@gmail.com',  168, 58, 57);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Micah', 'Spencer', 'Micah.Spencer@gmail.com',  185, 73, 32);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Lincoln', 'Marshall', 'Lincoln.Marshall@gmail.com', 165, 57, 53);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Jocelyn', 'Clements', 'Jocelyn.Clements@gmail.com',  153, 69, 57);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Adan', 'Macias', 'Adan.Macias@gmail.com',  175, 72, 38);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Gina', 'Houston', 'Gina.Houston@gmail.com',  170, 36, 58);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Curtis', 'Curtis', 'Curtis.Curtis@gmail.com',  157, 89, 52);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Aurora', 'Ashley', 'Aurora.Ashley@gmail.com',  159, 24, 45);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Zachariah', 'Juarez', 'Zachariah.Juarez@gmail.com',  196, 97, 44);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Alexa', 'Salinas', 'Alexa.Salinas@gmailgmail.com',  167, 58, 29);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Ignacio', 'Obrien', 'Ignacio.Obrien@gmailgmail.com',  201, 56, 42);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Santino', 'Boyle', 'Santino.Boyle@gmailgmail.com',  219, 55, 50);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Jean', 'Archer', 'Jean.Archer@gmailgmail.com',  212, 97, 29);
INSERT INTO public.data1(name_,surname_, email_, Height_, age_, shoesize) VALUES('Laurel', 'Dorsey', 'Laurel.Dorsey@gmail.com',  202, 86, 38);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Kody', 'Savage', 'Kody.Savage@hotmail.com' ,205, 96, 49);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Tyrone', 'Cervantes', 'Tyrone.Cervantes@gmail.com', 178, 89, 43);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Sawyer', 'bøffelmand', 'Sawyerbøffelmand@gmail.com' , 162, 77, 57);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Cade', 'Dillon', 'Cade.Dillon@outlook.com', 167, 49, 24);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Sidney', 'Terrell', 'Sidney.Terrell@hotmail.com', 209, 93, 50);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Weston', 'Lucas', 'Weston.Lucas@outlook.com', 203, 65, 36);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Kaylen', 'Sexton', 'Kaylen.Sexton@hotmail.com', 200, 51, 59);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Jaylee', 'Osborne', 'Jaylee.Osborne@outlook.com', 197, 84, 20);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Clara', 'Schmitt', 'Clara.Schmitt@hotmail.com', 190, 43, 39);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Joyce', 'Villarreal', 'Joyce.Villarreal@outlook.com', 172, 74, 43);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Marlie', 'Pitts', 'Marlie.Pitts@gmail.com', 161, 87, 31);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Noe', 'Welch', 'Noe.Welch@hotmail.com', 208, 46, 46);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Rubi', 'Gomez', 'Rubi.Gomez@hotmail.com', 168, 29, 57);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Davon', 'Pittman', 'Davon.Pittman@gmail.com', 184, 39, 43);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Yair', 'Mckenzie', 'Yair.Mckenzie@gmail.com', 161, 50, 26);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Dominik', 'Gould', 'Dominik.Gould@outlook.com', 176, 57, 37);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Emely', 'Benton', 'Emely.Benton@outlook.com', 150, 86, 39);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Daniel', 'Griffin', 'Daniel.Griffin@gmail.com', 158, 64, 23);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Tomas', 'Bruce', 'Tomas.Bruce@yahoo.com', 188, 84, 35);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Niko', 'Nash', 'Niko.Nash@gmail.com', 174, 38, 23);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Lorena', 'Little', 'Lorena.Little@hotmail.com', 168, 88, 28);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Brock', 'Boyer', 'Brock.Boyer@gmail.com ', 173, 45, 48);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Nina', 'Michael', 'Nina.Michael@outlook.com', 200, 71, 42);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Zoey', 'Yang', 'Zoey.Yang@outlook.com', 203, 88, 35);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Tatum', 'Sloan', 'Tatum.Sloan@yahoo.com', 203, 29, 53);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Sydnee', 'Santana', 'Sydnee.Santana@hotmail.com', 202, 81, 53);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Jalen', 'Shannon', 'Jalen.Shannon@hotmail.com', 198, 47, 54);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Teagan', 'Harris', 'Teagan.Harris@gmail.com', 154, 21, 50);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Mackenzie', 'Mejia', 'Mackenzie.Mejia@yahoo.com', 157, 39, 33);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Elyse', 'Madden', 'Elyse.Madden@gmail.com', 215, 92, 45);
INSERT INTO public.data1(name_, surname_, email_ ,height_, age_, shoesize) VALUES ('Sawyer', 'Huffman', 'Sawyer.Huffman@hotmail.com', 160, 95, 57);


